### Numpy Operations

In [1]:
import numpy as np

In [2]:
np_arr = np.arange(0, 11)

#### Vector operations

In [3]:
np_arr + np_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Scalar Operations

In [4]:
np_arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
# Sometimes wrong operations in the code doesn't raise any error. It will just post an warning.

np_arr / np_arr

/Users/ranvir/Documents/rgithub/datascience/venv/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Universal operations

In [6]:
np.sqrt(np_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [9]:
np.exp(np_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])