### Numpy selecting elements

In [1]:
import numpy as np

In [2]:
# Create a np array

np_arr = np.arange(0, 11)

In [3]:
np_arr[5]

5

### Index start from 0 and selecting is almost similar to python array selection

In [4]:
np_arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
np_arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
np_arr[:5]

array([0, 1, 2, 3, 4])

### Broadcasting to all values in np array: These are inline and change arrays permanently

In [13]:
# We can make changes to the elements using selection methods.

np_arr[0:5] = 100

In [14]:
np_arr

array([ 100,  100,  100,  100,  100, 5000, 5000, 5000, 5000, 5000, 5000])

In [15]:
sliced_np_arr = np_arr[5:]

In [16]:
sliced_np_arr[:] = 5000

In [17]:
# Changes are done directly to the np array.

np_arr

array([ 100,  100,  100,  100,  100, 5000, 5000, 5000, 5000, 5000, 5000])

### Use copy method if you don't want this to be done inline

In [18]:
np_copy = np_arr.copy()

In [20]:
np_copy[0:9] = -10

In [23]:
# See np_copy has changed.

np_copy

array([ -10,  -10,  -10,  -10,  -10,  -10,  -10,  -10,  -10, 5000, 5000])

In [24]:
# np_arr is still the same.

np_arr

array([ 100,  100,  100,  100,  100, 5000, 5000, 5000, 5000, 5000, 5000])

### Working on 2d arrays

In [37]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Double bracket format

In [39]:
arr_2d[0][0]

5

In [40]:
arr_2d[0]

array([ 5, 10, 15])

### Comma notation

In [41]:
arr_2d[1, 2]

30

In [42]:
arr_2d[1,]

array([20, 25, 30])

### Getting sections of array

In [44]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [45]:
# Grabbing last row

arr_2d[2:, 0:]

array([[35, 40, 45]])

### Conditional selecting

**We can use conditions to select certain parts of the arrays**

In [47]:
np_arr

array([ 100,  100,  100,  100,  100, 5000, 5000, 5000, 5000, 5000, 5000])

In [48]:
np_arr > 100

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [49]:
# It return all the elements where the array value is True

np_arr[np_arr > 100]

array([5000, 5000, 5000, 5000, 5000, 5000])