### NumPy Arrays

In [3]:
# Create a simple array

new_list = [1, 2, 3]

In [4]:
import numpy as np

In [8]:
# Create a vector from the given normal array.

numpy_arr = np.array(new_list)

In [9]:
numpy_arr

array([1, 2, 3])

### Creating an numpy martice using simple matrice

In [10]:
simple_matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np_matrice = np.array(simple_matrice)

In [12]:
np_matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Generating numpy array using numpy built in functions

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Adding a step size

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
# vector of zeros

np.zeros(3)

array([0., 0., 0.])

In [18]:
# Matrice of zeros

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# vector of ones

np.ones(4)

array([1., 1., 1., 1.])

In [21]:
# Martice of ones

np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# vector with fractional values

np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
# Identity matrice

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Creating random arrays

np.random.rand(5)

array([0.29796482, 0.97957311, 0.97050764, 0.76893469, 0.23767867])

In [28]:
# Matrice of random values

np.random.rand(5, 5)

array([[0.68316458, 0.4201338 , 0.9470722 , 0.78668396, 0.17177819],
       [0.22975645, 0.22660554, 0.06199722, 0.44489749, 0.26025632],
       [0.74081693, 0.59937798, 0.74905536, 0.8298967 , 0.16538886],
       [0.53176524, 0.06268803, 0.03459886, 0.439046  , 0.88222882],
       [0.61149478, 0.03849062, 0.73232594, 0.12622486, 0.80035998]])

In [29]:
# Generating random integers

np.random.randint(1, 100, 5)

array([20, 65, 26, 56, 86])

### Important methods of numpy arrays

In [30]:
np_arr = np.arange(25)

In [31]:
np_mat_arr = np.random.randint(0, 50, 10)

In [35]:
# Reshaping the vector and matrices
# Keep in mind these changes are not made to the variables themself.

np_arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
# np_arr is still a vector

np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
# maximum/ min value

np_mat_arr.max()

49

In [40]:
np_mat_arr.min()

9

In [41]:
# index location of min/ max

np_mat_arr.argmax()

7

In [43]:
# size of vector

np_arr.shape

(25,)

In [44]:
# size of matrice

np_arr.reshape(5, 5).shape

(5, 5)

In [45]:
# datatypes of np arrays

np_arr.dtype

dtype('int64')